export const formActionTypes = {
  INIT: "INIT",
  VALIDATION_FAIL: "VALIDATION_FAIL",
  VALIDATION_SUCCESS: "VALIDATION_SUCCESS",
  START_SUBMIT: "START_SUBMIT",
  SUBMIT_SUCCESS: "SUBMIT_SUCCESS",
  SUBMIT_FAIL: "SUBMIT_FAIL",
}
