version: 2.1

executors:
  node-image:
    docker:
      - image: cimg/node:12.22

jobs:
  build-and-deploy:
    executor: node-image
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: node deploy.js

workflows:
  version: 2
  monthly_deploy:
    triggers:
     - schedule:
         # Every month at 4am on 17th
         cron: "0 4 17 * *"
         filters:
           branches:
             only:
               - master
    jobs:
     - build-and-deploy
  tagged_deploy:
    jobs:
      - build-and-deploy:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
