version: 2.1

orbs:
  node: circleci/node@4.7.0

jobs:
  build-and-deploy:
    executor:
      name: node/default
      tag: '10.4'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run build
      - run: node deploy.js

workflows:
  version: 2
  monthly_deploy:
    triggers:
     - schedule:
         # Every month at 4am on 17th
         cron: "0 4 17 * *"
         filters:
           branches:
             only:
               - master
    jobs:
     - build-and-deploy
  tagged_deploy:
    jobs:
      - build-and-deploy:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
